export const APPLY_COUPON_REQUESTED = 'APPLY_COUPON_REQUESTED';
export const APPLY_COUPON_SUCCEEDED = 'APPLY_COUPON_SUCCEEDED';
export const APPLY_COUPON_FAILED = 'APPLY_COUPON_FAILED';

export const REMOVE_COUPON_REQUESTED = 'REMOVE_COUPON_REQUESTED';
export const REMOVE_COUPON_SUCCEEDED = 'REMOVE_COUPON_SUCCEEDED';
export const REMOVE_COUPON_FAILED = 'REMOVE_COUPON_FAILED';
