export const INITIALIZE_SHIPPING_REQUESTED = 'INITIALIZE_SHIPPING_REQUESTED';
export const INITIALIZE_SHIPPING_SUCCEEDED = 'INITIALIZE_SHIPPING_SUCCEEDED';
export const INITIALIZE_SHIPPING_FAILED = 'INITIALIZE_SHIPPING_FAILED';
