import type { CodegenConfig } from '@graphql-codegen/cli';

// Schema is a copy of the storefront GraphQL SDL. To refresh it:
// 1. Copy src/main/resources/graphql/autogenerated/schema.graphql from the
//    storefront repository.
// 2. Run `sed -i '' 's/scope: Public/scope: PUBLIC/g'` on the copy — the
//    upstream SDL applies @cacheControl(scope: Public) while the enum value
//    is PUBLIC, which strict validation rejects.
// 3. Re-run `npm run codegen`.
const config: CodegenConfig = {
    schema: 'packages/core/schema/storefront.graphql',
    documents: ['packages/core/src/**/*.graphql'],
    generates: {
        'packages/core/src/__generated__/': {
            preset: 'client',
            presetConfig: {
                fragmentMasking: false,
            },
            config: {
                documentMode: 'string',
                enumsAsTypes: true,
                skipTypename: true,
                immutableTypes: true,
                onlyOperationTypes: true,
            },
        },
    },
};

export default config;
